name: flask-ci-test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup library
        run: |
          pip install -r requirements.txt
          pip install pipenv
      - name: Populate yaml
        run: |
          echo "${{ secrets.flaskr }}" > .env
          pipenv run populate
      - name: init db
        run: pipenv init_db
      - name: Execute pytest
        run: pipenv test
