name: flask-ci-test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup library
        run: |
          pip install -r requirements.txt
          pip install pipenv
          pipenv sync --dev
      - name: Populate yaml
        env:
          FLASK_APP: ${{ secrets.FLASK_APP }}
          FLASK_ENV: ${{ secrets.FLASK_ENV }}
          CONTRAST_API_KEY: ${{ secrets.CONTRAST_API_KEY }}
          CONTRAST_SERVICE_KEY: ${{ secrets.CONTRAST_SERVICE_KEY }}
          CONTRAST_URL: ${{ secrets.CONTRAST_URL }}
          CONTRAST_USER_NAME: ${{ secrets.CONTRAST_USER_NAME }}
        run: |
          echo ${FLASK_APP}
          echo ${FLASK_ENV}
          pipenv run populate
      - name: init db
        run: |
          pipenv shell
          pipenv run init_db
      - name: Execute pytest
        run: pipenv test
